os: windows
language: C++
branches:
  only:
  - main
before_install:
  - wget -q https://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe -O qt-unified-windows-x86-online.exe
install:
  - ./qt-unified-windows-x86-online.exe --script ./.ci/qt_installer_windows.qs -d
script:
  - qmake SolarSystem.pro
